#!/bin/bash

case $1 in
    'one')
apt install -y bash-completion bison debhelper default-jdk flex javahelper libmysql++-dev libsqlite3-dev libssl-dev libsystemd-dev libws-commons-util-java libxml2-dev libxmlrpc3-client-java libxmlrpc3-common-java libxslt1-dev libcurl4-openssl-dev libcurl4 ruby scons libxmlrpc-c++8-dev libvncserver-dev
    ;;
    'packages')
apt-get install -y pbuilder debhelper ubuntu-dev-tools bash-completion \
bison default-jdk flex javahelper libxmlrpc3-client-java \
libxmlrpc3-common-java libxml2-dev ruby scons
    ;;
    'infra')
apt install uuid-runtime curl ruby-ronn npm git nodejs-legacy openjdk-8-jdk opennebula-tools libxmlrpc3-client-java yard sshuttle software-properties-common
apt-add-repository ppa:ansible/ansible
apt-get update
apt-get install ansible
    ;;
    *) echo 'one/packages/infra'
    ;;
esac
